const palavras = [
    palavra001={
        nome:"IRLANDA",
        categoria:"PAISES",
    },
    palavra002={
        nome:"BRASIL",
        categoria:"PAISES",
    },
    palavra003={
        nome:"ARGENTINA",
        categoria:"PAISES",
    },
    palavra004={
        nome:"PIZZA",
        categoria:"COMIDA",
    },
    palavra005={
        nome:"HAMBURGUER",
        categoria:"COMIDA",
    },
    palavra006={
        nome:"COMPUTADOR",
        categoria:"OBJETOS",
    },
    palavra007={
        nome:"BANANA",
        categoria:"FRUTA",
    },
    palavra008={
        nome:"ABACATE",
        categoria:"FRUTA",
    },
]